-- Row-level security for Agentsy (PostgreSQL).
--
-- SOURCE OF TRUTH: ../drizzle/0001_extensions_rls_triggers.sql
-- Apply via Drizzle (recommended):
--   DATABASE_URL=... pnpm --filter @agentsy/db db:migrate
--
-- Do not hand-apply this file; it remains as a human-readable mirror only.
-- When changing RLS, edit the migration chain:
--   pnpm --filter @agentsy/db exec drizzle-kit generate --custom --name <desc>
--   (or adjust 0001 before any environment has applied it, then never rewrite applied migrations.)

-- See ../drizzle/0001_extensions_rls_triggers.sql (RLS section).
